from tkinter import *
from tkinter import ttk
import pandas as pd
import pip
pip.main(['install', 'catboost'])
from catboost import CatBoostRegressor


def motorcicle():

    def test():

        condition = {'New': 0, 'Used': 1}
        color = {'100TH Anniversary': 0,
 '105 Anniversary Copper': 1,
 '2 Tone Vivid Black and Smokey Gold': 2,
 '2-Tone Black &amp; Blue': 3,
 '2-Tone Pacific Blue Pearl and Vivid Black': 4,
 '2-Tone Red and Black': 5,
 '2-Tone Sinister Blue and Diamond Ice Silver': 6,
 '4 colors': 7,
 '60th Anniversary': 8,
 'ALPINE WHITE': 9,
 'ALUMINIUM SILVER': 10,
 'AMBER': 11,
 'APPLE GREEN/BLACK': 12,
 'APPLE RED CANDY': 13,
 'AQUA': 14,
 'Algerian blue': 15,
 'Amber Whiskey': 16,
 'Amber Whisky': 17,
 'Anniversary Colors': 18,
 'Anniversary Copper Pearl/Black Onyx': 19,
 'Anniversary Vintage Bronze/Anniversary Vintage Black': 20,
 'Aqua Pearl': 21,
 'Army Fatigue': 22,
 'Atomic Red with Candy Apple Red Flames': 23,
 'BEIGE': 24,
 'BIARRITZ BLUE METALLIC': 25,
 'BIEGE': 26,
 'BIG BLUE PEARL': 27,
 'BIG FLAKE RED': 28,
 'BILLET SILVER': 29,
 'BKUE': 30,
 'BL/WT/RD': 31,
 'BLACK': 32,
 'BLACK &amp; BLUE': 33,
 'BLACK &amp; ORANGE': 34,
 'BLACK &amp; RED': 35,
 'BLACK / GRAY': 36,
 'BLACK AN PEARL WHITE': 37,
 'BLACK AND PEARL WHITE': 38,
 'BLACK AND WHITE': 39,
 'BLACK CHERRY': 40,
 'BLACK CHERRY PREAL': 41,
 'BLACK DEN': 42,
 'BLACK DENIM': 43,
 'BLACK DIAMOND': 44,
 'BLACK HILLS GOLD/BLACK QUARTZ': 45,
 'BLACK ICE/ELECTRIC ORANGE': 46,
 'BLACK N WHITE': 47,
 'BLACK PEARL': 48,
 'BLACK QUARTZ': 49,
 'BLACK SMOKE': 50,
 'BLACK STORM METALLIC': 51,
 'BLACK W/ PINSTRIPE': 52,
 'BLACK W/FLAMES': 53,
 'BLACK WITH PINSTRIPE': 54,
 'BLACK/CHROME': 55,
 'BLACK/DARK RED': 56,
 'BLACK/FLAMES': 57,
 'BLACK/GOLD': 58,
 'BLACK/GREEN': 59,
 'BLACK/RED': 60,
 'BLACK/RED W/GRAPHICS': 61,
 'BLACK/SILVER': 62,
 'BLACK/SILVER/RED': 63,
 'BLACK/WHITE': 64,
 'BLACK/WHITE/GREY': 65,
 'BLACKCHERRY': 66,
 'BLK': 67,
 'BLK/CRM': 68,
 'BLK/GRY': 69,
 'BLUE': 70,
 'BLUE / BLACK': 71,
 'BLUE / SILVER': 72,
 'BLUE METALLIC': 73,
 'BLUE/BLACK': 74,
 'BLUE/PURPLE': 75,
 'BLUE/SILVER': 76,
 'BLUE/WHITE': 77,
 'BRONZE': 78,
 'BRONZE/BLACK': 79,
 'BURG/MAROON': 80,
 'BURGANDY': 81,
 'BURGUNDY BLAZE/HOT FUSION GRAPHICS': 82,
 'Beige': 83,
 'Big Blue Pearl': 84,
 'Big Pearl Blue': 85,
 'Birch White &amp; Midnight Pearl': 86,
 'Birch White and Red': 87,
 'Bk red white': 88,
 'Blach &amp; Yellow': 89,
 'Blachberry Metalic/Black': 90,
 'Black': 91,
 'Black  Denim': 92,
 'Black &amp; Chrome': 93,
 'Black &amp; Gray': 94,
 'Black &amp; Red': 95,
 'Black &amp; Silver': 96,
 'Black &amp; White': 97,
 'Black &amp; White Ice  (Blue &amp; White)': 98,
 'Black &amp; other colors': 99,
 'Black / Gray': 100,
 'Black / Yellow': 101,
 'Black / copper': 102,
 'Black Blue Red Green': 103,
 'Black Bronze metalflake': 104,
 'Black Cherry': 105,
 'Black Cherry &amp; Gray': 106,
 'Black Cherry Pearl': 107,
 'Black Cherry Pearl/Black Pearl': 108,
 'Black Cherry Pearl/Pewter Pearl': 109,
 'Black Cherry Red': 110,
 'Black Cherry/Grey': 111,
 'Black Denim': 112,
 'Black Diamond / Fire Quartz': 113,
 'Black Ice Denim / Purple': 114,
 'Black Metal flake': 115,
 'Black Metallic': 116,
 'Black Pearl': 117,
 'Black Pearl Metallic': 118,
 'Black Pearl/Red': 119,
 'Black Quartz': 120,
 'Black Quartz metallic': 121,
 'Black Storm Metallic': 122,
 'Black W/ Subtle Metallic Blue Spec': 123,
 'Black W/ White pinstriping': 124,
 'Black and Chrome': 125,
 'Black and Orange': 126,
 'Black and Red': 127,
 'Black and White': 128,
 'Black and chrome': 129,
 'Black and silver': 130,
 'Black ember &amp; rio red flames': 131,
 'Black w/ Maroon': 132,
 'Black with Blue flames': 133,
 'Black with Flames': 134,
 'Black with Red': 135,
 'Black with Red Ghost Flames': 136,
 'Black with custom blue paint job': 137,
 'Black with faint blue sparkles.': 138,
 'Black/ Brown': 139,
 'Black/Blue': 140,
 'Black/Cream 2-tone': 141,
 'Black/Flames': 142,
 'Black/Gold': 143,
 'Black/Green': 144,
 'Black/Orange': 145,
 'Black/Pink': 146,
 'Black/Red': 147,
 'Black/White': 148,
 'Black/Yellow': 149,
 'Black/brown': 150,
 'Blackand White': 151,
 'Blackened Cayenne': 152,
 'Blackened Cayenne Sunglo': 153,
 'Blk': 154,
 'Blue': 155,
 'Blue &amp; Silver': 156,
 'Blue &amp; Silver Metallic': 157,
 'Blue / BLACK': 158,
 'Blue / Black': 159,'Blue / Orange': 160,
 'Blue / White': 161,
 'Blue Cepheus': 162,
 'Blue Metallic': 163,
 'Blue Metallic with Black': 164,
 'Blue Sapphire &amp; Brilliant Blue': 165,
 'Blue Silver': 166,
 'Blue and Silver': 167,
 'Blue and White': 168,
 'Blue and pearl white': 169,
 'Blue and silver': 170,
 'Blue or Black': 171,
 'Blue, White': 172,
 'Blue/BLK': 173,
 'Blue/Black': 174,
 'Blue/Black Stripe': 175,
 'Blue/Green Metallic': 176,
 'Blue/Ivory Cream': 177,
 'Blue/Silver': 178,
 'Blue/White': 179,
 'Blue/White/Red': 180,
 'Blue/black': 181,
 'Blue/silver': 182,
 'Brandy Wine': 183,
 'Brandy Wine Pearl': 184,
 'Brilliance White Pearl &amp; Mandarine Orange Pearl': 185,
 'Brilliant Silver Pearl/Vivid Black': 186,
 'Bronze': 187,
 'Bronze Mist': 188,
 'Brown': 189,
 'Burgandy': 190,
 'Burgandy / cream': 191,
 'Burgundy': 192,
 'Burgundy (not sure exact color)': 193,
 'Burgundy Metallic': 194,
 'Burgundy gold ': 195,
 'Burgundy/Black CVO': 196,
 'CAMO': 197,
 'CANDY APPLE RED': 198,
 'CANDY ARABIAN RED': 199,
 'CANDY ORANGE': 200,
 'CANYON COPPER / ONYX': 201,
 'CARBON DUST &amp; CHARCOAL SLATE': 202,
 'CARBON DUST AND CHARCOAL SLATE': 203,
 'CARBON/RED': 204,
 'CHARCOAL': 205,
 'CHARCOAL DENIM': 206,
 'CHARCOAL PEARL': 207,
 'CHARCOAL PEARL/VIVID BLACK': 208,
 'CHARCOAL W/GHOST FLAMES': 209,
 'CHARLCOAL PEARL': 210,
 'CHROME': 211,
 'CLASSIC CREAM/MAROON': 212,
 'COMPETITION GREEN W/GOLD TANK STRIPE': 213,
 'COMPETITION GREEN/FROZEN SILVER': 214,
 'COPPER': 215,
 'COPPER AND BLACK': 216,
 'CORDOBA BLUE': 217,
 'COSMIC BLUE': 218,
 'CRANBERRY RED': 219,
 'CRANBERRY RED/ALUMINIUM SILVER': 220,
 'CRIMSON': 221,
 'CRUSH DIAMOND DUST/OBSIDIAN': 222,
 'CRYSTAL WHITE': 223,
 'CRYSTAL WHITE METALLIC': 224,
 'CUSTOM': 225,
 'CUSTOM AIR BRUSHED REAPER THEME': 226,
 'CUSTOM ROOT BEER AN BLACK': 227,
 'Candy Apple Metal Flake': 228,
 'Candy Apple Red': 229,
 'Candy Cardinal Red': 230,
 'Candy Concord': 231,
 'Candy HD Orange': 232,
 'Candy Indy Blue': 233,
 'Candy Lime Green/Metallic Spark Black': 234,
 'Candy Muse Red With Gold Pin-Stripes': 235,
 'Candy Orange / Metallic Red': 236,
 'Candy Orange/ Beer Bottle': 237,
 'Candy Red': 238,
 'Candy Red and Gloss Black': 239,
 'Candy Red or Gray': 240,
 'Candy Teal powder coat': 241,
 'Candy Thunder Blue': 242,
 'Candy apple red': 243,
 'Canyon Copper/Candy red': 244,
 'Carbon Fiber': 245,
 'Cascade Green Metallic': 246,
 'Caspian Blue': 247,
 'Chameleon': 248,
 'Charcoal ': 249,
 'Charcoal Denim': 250,
 'Charcoal Grey': 251,
 'Charcoal Pearl': 252,
 'Charcoal Silver': 253,
 'Charcoal Slate and Carbon Dust': 254,
 'Charcoal denim/grey denim': 255,
 'Cherry Red': 256,
 'Cherry Red Sunglow / Merlot Sunglow': 257,
 'Cherry red metallic': 258,
 'Cherry/merlot': 259,
 'Chrome': 260,
 'Chrome Yellow': 261,
 'Cobalt Blue': 262,
 'Cobalt/Pewter': 263,
 'Cognac': 264,
 'Cool Blue': 265,
 'Copper': 266,
 'Copper pearl Sparkle': 267,
 'Copper/Black': 268,
 'Cosmic Blue Pearl': 269,
 'Crimson &amp; Cream': 270,
 'Crimson Red Sunglo &amp; Candy Red Sunglo': 271,
 'Crimson Red Sunglo Metallic': 272,
 'Crushed Ice Pearl': 273,
 'Crystal Citron and Diamond Dust': 274,
 'Crystal Copper and Black Onyx': 275,
 'Crystal White / Jet Black': 276,
 'Crystal White Tricoat': 277,
 'Custom': 278,
 'Custom &#034;Earthquake&#034;': 279,
 'Custom 2 Tone Blue': 280,
 'Custom Airbrushed Paint Job': 281,
 'Custom Aqua Blue with Flames': 282,
 'Custom Black/Gold': 283,
 'Custom Blue Flames': 284,
 'Custom Color': 285,
 'Custom Factory Color #118/200': 286,
 'Custom Grim Reaper': 287,
 'Custom Orange/Black': 288,
 'Custom Paint': 289,
 'Custom Paint - Tangerine Flake': 290,
 'Custom Paint Job': 291,
 'Custom Pinstriping/Gold Leafing': 292,
 'Custom Red': 293,
 'Custom Two-tone Root Beer': 294,
 'Custom black/white lace': 295,
 'Custom blue/grey': 296,
 'Custom skull and flames': 297,
 'Custon': 298,
 'DARK &amp; LIGHT ROOT BEER': 299,
 'DARK BLUE': 300,
 'DEEP JADE PEARL': 301,
 'DIABLO RED': 302,
 'DIABLO RED/BLACK': 303,
 'DIABLO RED/MATT ALUMINUM': 304,
 'Dark Blue': 305,
 'Dark and Light Candy Rootbeer': 306,'Dark green': 307,
 'Daytona Blue Pearl': 308,
 'Daytona Orange': 309,
 'Deep Cobalt Pearl / Brilliant Silver Pearl': 310,
 'Deep Cobalt Pearl/Pewter Pearl': 311,
 'Deep Jade Pearl': 312,
 'Deep Purple': 313,
 'Deep Sherwood Pearl and Galactic Black': 314,
 'Denim Black': 315,
 'Denim black': 316,
 'Diamond Ice Silver': 317,
 'Diamond Ice/ Black': 318,
 'Digital Camo': 319,
 'EBONY MET': 320,
 'EMBER RED SUNGLO': 321,
 'ESPRESSO': 322,
 'ESPRESSO METALLIC': 323,
 'Ebony Metallic': 324,
 'El Toro Orange': 325,
 'Electric Yellow/Black Diamond': 326,
 'Electric orange/ Vivid Black': 327,
 'Ember Red Sunglo': 328,
 'Enber red sunglow/Merlot': 329,
 'FLAT BLACK': 330,
 'FUSION WHITE/AEGEAN BLUE': 331,
 'Factory Numbered Paint Set': 332,
 'Fire Red Pearl': 333,
 'Fireball Red &amp; White Lightening w Graphics': 334,
 'Flat Black': 335,
 'G156P Pearl Sierra Green  IT&#039;S SHARP!': 336,
 'GOLD RUSH/CABON W/PIN STRIPE': 337,
 'GRAPHITE': 338,
 'GRAY': 339,
 'GRAY/ RED': 340,
 'GRAY/ WHITE': 341,
 'GREEN': 342,
 'GREEN/BLACK': 343,
 'GREY': 344,
 'GREY &amp; RED': 345,
 'GREY/BLACK': 346,
 'GRY/BLK': 347,
 'Ghost Flames': 348,
 'Glacier Silver': 349,
 'Gloss Sunset Red': 350,
 'Gold': 351,
 'Gold ': 352,
 'Gold &amp; Brown': 353,
 'Gold Flake': 354,
 'Gold and Black': 355,
 'Golden Blazed Green / Metallic Spark Black': 356,
 'Graphite': 357,
 'Graphite Blue': 358,
 'Gray': 359,
 'Gray &amp; Black': 360,
 'Gray &amp; Green Two-Tone': 361,
 'Gray / White': 362,
 'Gray Metallic': 363,
 'Gray and Burg Metallic': 364,
 'Gray and Ebony Metallic 2 tone': 365,
 'Green': 366,
 'Green Metallic': 367,
 'Green demons': 368,
 'Green or Gray': 369,
 'Green/Black': 370,
 'Green/Silver': 371,
 'Green/White/Purple': 372,
 'Grey': 373,
 'Grey / Red / Silver Metallic': 374,
 'Grey metallic': 375,
 'Guards Red/Winter White': 376,
 'Gun Metal': 377,
 'Gun Metal Blue': 378,
 'Gunmetal Grey': 379,
 'HARD CANDY CUSTOM': 380,
 'HOT Citrus/Antique Gunstock w/ Phantom Flame graph': 381,
 'Hard Candy Gold': 382,
 'Hard Candy Gold/Black Flake': 383,
 'House of Colors Tangello Pearl Orange': 384,
 'ICEBURG SILVER': 385,
 'ICON Red and Black (Matte)': 386,
 'INDIAN MOTORCYCLE RED': 387,
 'IR/BLK': 388,
 'IRONESTONE': 389,
 'Illusion Blue': 390,
 'Impact Blue': 391,
 'Indian Red/Thunder Black': 392,
 'JADE SUNGLO': 393,
 'JET BLACK': 394,
 'JET BLACK/SILVER ICE': 395,
 'Jade': 396,
 'Jet Black': 397,
 'Kandy brandywine': 398,
 'LAVA RED': 399,
 'LIGHT GREY METALLIC': 400,
 'LIGHT WHITE': 401,
 'LIME': 402,
 'LIME GREEN': 403,
 'Laser Red Metallic': 404,
 'Lava Red': 405,
 'Light Blue / White': 406,
 'Light Brown': 407,
 'Light Grey / Sapphire Black': 408,
 'Light White': 409,
 'Lime Green': 410,
 'Limited - Matte Silver': 411,
 'Limited 2004 color': 412,
 'Liquid Graphite': 413,
 'Lucerne Blue': 414,
 'Luxury Rich Red': 415,
 'Luxury Rich Red Pearl': 416,
 'Luxury Rich Red/ Champaine': 417,
 'MAGNESIUM BEIGE METALLIC': 418,
 'MAPLE/BLACK': 419,
 'MARBLE RED HAZE': 420,
 'MAROON': 421,
 'MAROON RED': 422,
 'MATT GRAPHITE': 423,
 'MATTE ALUMINIUM SILVER': 424,
 'MATTE BLACK': 425,
 'MATTE GRAPHITE': 426,
 'MATTE GRAY': 427,
 'MATTE GREY': 428,
 'MATTE KHAKI GREEN': 429,
 'MATTE PHANTOM BLACK': 430,
 'MATTE PHANTOM BLACK/MATTE ALUMINUM SILVER': 431,
 'MATTE SILVER': 432,
 'MATTE SILVER ICE': 433,
 'MATTEBLK': 434,
 'MERLIN RED': 435,
 'MERLOT': 436,
 'METALIC BLACK/MAROON FLAMES': 437,
 'METALLIC MATTE CARBON GRAY': 438,
 'MIDNIGHT BLUE': 439,
 'MIDNIGHT PRL': 440,
 'MIDNIGHT/BRILLIANT SILVER': 441,
 'MORELLO RED': 442,
 'MYS Red': 443,
 'MYSTERIOUS RED SUNGLO': 444,
 'Mareum Blue': 445,
 'Maroon': 446,
 'Maroon/Tan': 447,
 'Matt Green': 448,
 'Matte Altair Silver': 449,
 'Matte Black': 450,
 'Matte Gray': 451,
 'Matted Black': 452,
 'Merlot Sunglo': 453,
 'Merlot Sunglo with Pinstripe Graphics': 454,
 'Metalic Smoke Grey': 455,
 'Metallic Blue': 456,
 'Metallic Flat Spark Black/Metallic Spark Black': 457,
 'Metallic Matte Titanium': 458,
 'Metallic Spark Black': 459,
 'Metallic black': 460,
 'Mettalic blue': 461,
 'Midnight Black': 462,'Midnight Cherry': 463,
 'Midnight Pearl': 464,
 'Military Green': 465,
 'Monolith Metallic Matt / Sapphire Black Metallic': 466,
 'Monolith Metallic Matte': 467,
 'Montego Blue Metallic': 468,
 'Monza Blue': 469,
 'Morocco Gold Pearl': 470,
 'Mother of Pearl White': 471,
 'Mysterious Red Sunglo': 472,
 'Mysterious Red Sunglo/Blackened Cayenne Sunglo': 473,
 'Mysterious Red Sunglo/Velocity Red Sunglo': 474,
 'NEW ENGLAND WHITE/INTENSE ORANGE': 475,
 'NH469M Stream Silver Metalic  IT&#039;S SHARP!': 476,
 'NVY BL': 477,
 'Neutron Green Metallic': 478,
 'OBSIDIAN / DIAMOND DUST': 479,
 'OCEAN BLUE METALLIC': 480,
 'OD Green': 481,
 'OLIVE GREEN DENIM': 482,
 'ORANGE': 483,
 'ORANGE PEARL': 484,
 'OSTRA GRAY': 485,
 'Ocean Blue': 486,
 'Olive Gold': 487,
 'Onyx': 488,
 'Orange': 489,
 'Orange / Cream': 490,
 'Orange / White': 491,
 'Orange Madness': 492,
 'Orange Pearl and Jet Black': 493,
 'Orange and Black': 494,
 'Orange/Black': 495,
 'Oreanish Red and White': 496,
 'Other': 497,
 'PEARL GLACIER WHITE': 498,
 'PEARL WHITE': 499,
 'PEWTER PEARL': 500,
 'PEWTER PEARL/ PEARL WHITE': 501,
 'PHANTOM BLACK': 502,
 'PURE WHITE': 503,
 'PURPLE': 504,
 'Pacific Blue Pearl': 505,
 'Pearl Black': 506,
 'Pearl Crystal White': 507,
 'Pearl Glacier White': 508,
 'Pearl Nebular Black': 509,
 'Pearl Sapphire Black': 510,
 'Pearl White': 511,
 'Pearl White/Chamleon Pearl': 512,
 'Pearl/Silver': 513,
 'Pewter Pearl': 514,
 'Pewter Pearl / Silver Metallic': 515,
 'Purple': 516,
 'Purple Violet': 517,
 'Quartz Blue Metallic': 518,
 'R259P Canyan Red...  IT&#039;S SHARP!': 519,
 'RACING YELLOW/SILVER ICE': 520,
 'RED': 521,
 'RED AND BLACK': 522,
 'RED BLACK': 523,
 'RED METALLIC W/FLAMES': 524,
 'RED WHITE': 525,
 'RED/ BLACK': 526,
 'RED/BLACK': 527,
 'RED/CRM': 528,
 'RED/SILV': 529,
 'RED/SILVER': 530,
 'RED/WHITE': 531,
 'RED/WHITE/BLACK': 532,
 'RED/WHITE/BLUE': 533,
 'RICH RED W/STRIPES': 534,
 'Radioactive': 535,
 'Raven': 536,
 'Raw metal': 537,
 'Red': 538,
 'Red  flame': 539,
 'Red &amp; Black': 540,
 'Red &amp; Silver': 541,
 'Red &amp; White': 542,
 'Red / Ivory': 543,
 'Red / White': 544,
 'Red / white': 545,
 'Red Apple Metallic': 546,
 'Red Blue Orange  White Green': 547,
 'Red Hot Sun Glo': 548,
 'Red Hot Sunglo': 549,
 'Red Hot Sunglow': 550,
 'Red Hot Sunglow/Smokey Gold': 551,
 'Red Metal flake': 552,
 'Red White Blue': 553,
 'Red White and Black': 554,
 'Red and White': 555,
 'Red w/pin stripes': 556,
 'Red, White, Black': 557,
 'Red/ Black': 558,
 'Red/Black': 559,
 'Red/Green': 560,
 'Red/Silver': 561,
 'Red/White': 562,
 'Red/White/Blue': 563,
 'Red/gray': 564,
 'Red/white': 565,
 'Red/yellow': 566,
 'Repsol Edition Graphics': 567,
 'Rich Sunglo Blue': 568,
 'Roman Gold and Emerald': 569,
 'S.S. RED': 570,
 'SAND CAMO DENIM': 571,
 'SATIN BLACK &amp; ORANGE': 572,
 'SATIN BLACK &amp; RED': 573,
 'SCARLET RED': 574,
 'SILVER': 575,
 'SILVER / YELLOW': 576,
 'SILVER BLACK': 577,
 'SILVER/BLACK': 578,
 'SILVER/GRAY FLAME': 579,
 'SILVER/GREY': 580,
 'SILVER/PURPLE FLAME': 581,
 'ST GRAY': 582,
 'STARDUST SILVER/AUTUMN SUNSET': 583,
 'STARFIRE BLACK': 584,
 'SUPERIOR BLUE': 585,
 'Sand Pearl': 586,
 'Sapphire Black Metallic': 587,
 'Sapphire Blue': 588,
 'Satin White': 589,
 'Scarlet Red': 590,
 'Scarlet Red/Black': 591,
 'Sedona Orange': 592,
 'See Pictures': 593,
 'Sierra Red': 594,
 'Silve': 595,
 'Silver': 596,
 'Silver &amp; teal': 597,
 'Silver Matte': 598,
 'Silver Smoke': 599,
 'Silver and Black': 600,
 'Silver with Ghost Flames': 601,
 'Silver/Black': 602,
 'Silver/Black/Chrome': 603,
 'Silver/Gray': 604,
 'Silver/Green': 605,
 'Silver/Grey': 606,
 'Silver/charcoal': 607,
 'Smokey Gold': 608,
 'Special Edition Yellow': 609,
 'Stars&amp;stripes': 610,
 'Steel Gray &amp; Thunder Black': 611,
 'Steel Gray / Burgundy': 612,
 'Street Glide FLHXSE2': 613,
 'Suede Titanium Metallic': 614,
 'Sun glo merlot': 615,
 'Sunrise Orange': 616,
 'Superior Blue': 617,
 'Superipr Blue': 618,
 'Superpole': 619,
 'TEAL/ WHITE': 620,
 'TEAL/CREME': 621,
 'THUNDER GREY MET': 622,
 'TITAN SILVER': 623,
 'TITANIUM': 624,'TITANIUM SILVER': 625,
 'TITATIUM': 626,
 'TRIBAL ORANGE': 627,
 'TURQUOIS,BLUE': 628,
 'TWO TONE': 629,
 'Tan': 630,
 'Teal': 631,
 'Teal and white': 632,
 'Tequila Sunrise': 633,
 'Terracotta': 634,
 'Thunder Black': 635,
 'Thunder Black Smoke': 636,
 'Thunder Black over Cream': 637,
 'Tricolore': 638,
 'Turbo Silver': 639,
 'Turbos Silver': 640,
 'Turquoise with Custom Graphics': 641,
 'Two Tone Grey': 642,
 'Two-Tone Birch White / Midnight Pearl': 643,
 'Urban Camo Edition': 644,
 'Urban Camouflage': 645,
 'VIVID BLACK': 646,
 'Valencia Orange Metallic': 647,
 'Velocity Red': 648,
 'Velocity Red Mica': 649,
 'Velocity Red Sunglo': 650,
 'Venom Yellow': 651,
 'Violet Pearl': 652,
 'Violet Pearl/Red Pearl Two Tone': 653,
 'Vivid Black': 654,
 'Vivid Black / White Pearl': 655,
 'Vivid Black and Birch White': 656,
 'WHITE': 657,
 'WHITE AND SILVER': 658,
 'WHITE BLACK': 659,
 'WHITE PEARL BLUE PEARL': 660,
 'WHITE SMOKE': 661,
 'WHITE/BLACK': 662,
 'WHITE/BLUE': 663,
 'WHITE/GREEN': 664,
 'WHITE/RED': 665,
 'WHITE/TEAL': 666,
 'WHT': 667,
 'WOODLANDS CAMO': 668,
 'White': 669,
 'White -Red-Blue': 670,
 'White / Black': 671,
 'White / Blue': 672,
 'White / Gray Pearl': 673,
 'White / Red': 674,
 'White red': 675,
 'White/Black/Green/Gold': 676,
 'White/Black/Orange': 677,
 'White/Blue': 678,
 'White/Chrome/Black': 679,
 'White/Red': 680,
 'White/Silver': 681,
 'White/Teal two tone': 682,
 'White/green': 683,
 'White/orange': 684,
 'White/silver': 685,
 'Wht': 686,
 'Wildfire Red Over Thunder Black': 687,
 'Wineberry Red': 688,
 'YELLOW': 689,
 'YELLOW FLAME': 690,
 'YELLOW METALLIC FINISH': 691,
 'YELLOW W/ RED TRIBLE': 692,
 'YELLOW/BLACK': 693,
 'YELLOW/FLAMES': 694,
 'Yellow': 695,
 'Yellow Metallic': 696,
 'Yellow and Black': 697,
 'Yellow//Black': 698,
 'Yellow/Graphite': 699,
 'Yellow/Purple': 700,
 'Yellow/Red': 701,
 'all': 702,
 'bLUE': 703,
 'black': 704,
 'black carbon': 705,
 'black cherry': 706,
 'black green': 707,
 'black lime green white': 708,
 'black powder coat': 709,
 'black-silver special': 710,
 'black/creme': 711,
 'black/green': 712,
 'bleu': 713,
 'blk': 714,
 'blk smk': 715,
 'blu': 716,
 'blue': 717,
 'blue and white': 718,
 'blue/green/silver': 719,
 'blue/silver': 720,
 'blue/white': 721,
 'burgandy and silver with reddish pin stripe': 722,
 'burgany w/ graphics': 723,
 'candy apple red': 724,
 'candy apple red/black graphics': 725,
 'charcoal': 726,
 'charcoal gray': 727,
 'charcoal pearl': 728,
 'copper/black': 729,
 'custom': 730,
 'custom orange': 731,
 'custom red wood grain/black/siver': 732,
 'flame custom': 733,
 'gold-multi-color custom': 734,
 'green': 735,
 'green blue or red': 736,
 'liquid graphite': 737,
 'maroon': 738,
 'metallic Red Custom Flames': 739,
 'moroccan gold pearl': 740,
 'multible colors': 741,
 'old shool orange': 742,
 'onyx': 743,
 'red': 744,
 'red and black': 745,
 'red/black': 746,
 'red/white': 747,
 'satin black': 748,
 'see photos': 749,
 'silver': 750,
 'sinister blue': 751,
 'suede green': 752,
 'titanium': 753,
 'two tone rootbeer': 754,
 'violet blue': 755,
 'white': 756,
 'white pearl metallic': 757,
 'white pearl with candy flames': 758,
 'white pearlescent': 759,
 'yellow': 760}
        brands = {'ADVANTAGE': 0,
 'American Classic Motors': 1,
 'American IronHorse': 2,
 'American Ironhorse': 3,
 'Aprilia': 4,
 'BETA': 5,
 'BMW': 6,
 'BSA': 7,
 'Benelli': 8,
 'Big Bear Choppers': 9,
 'Big Dog': 10,
 'Bimota': 11,
 'Boss Hoss': 12,
 'Bourget': 13,
 'Buell': 14,
 'Bultaco': 15,
 'Campagna': 16,
 'Can-Am': 17,
 'Cushman': 18,
 'Custom Built Motorcycles': 19,
 'Ducati': 20,
 'GMC': 21,
 'Harley-Davidson': 22,
 'Honda': 23,
 'Husqvarna': 24,
 'Hyosung': 25,
 'Indian': 26,
 'Indian MotorcycleВ®': 27,
 'KTM': 28,
 'Kawasaki': 29,
 'MV Agusta': 30,
 'Moto Guzzi': 31,
 'Norton': 32,
 'Other Makes': 33,
 'Piaggio': 34,
 'Polaris': 35,
 'Polaris SlingshotВ®': 36,
 'Royal Enfield': 37,
 'Slingshot': 38,
 'Suzuki': 39,
 'Swift Motor Co.': 40,
 'Triumph': 41,
 'Ultimate': 42,
 'Ural': 43,
 'Victory': 44,
 'Wild West': 45,
 'Yamaha': 46}
        type = {'--': 0,
 '1200X': 1,
 '3 Wheels': 2,
 '3-Wheel Side x Side Motorcycle': 3,
 'ADV.': 4,
 'AWESOME!': 5,
 'Adventure': 6,
 'Adventure-Sport': 7,
 'Aermacchi': 8,
 'American Eagle': 9,
 'Antique': 10,
 'Aspencade': 11,
 'Bagger': 12,
 'Banking three wheeler': 13,
 'Bar Hopper': 14,
 'Bar hopper': 15,
 'Blazer': 16,
 'Bobber': 17,
 'CB': 18,
 'CBR': 19,
 'CHOPPER': 20,
 'CRUISER': 21,
 'CRUISRER': 22,
 'CUSTOM': 23,
 'CUSTOM BIKE': 24,
 'CUSTOM CHOPPER': 25,
 'CVO Screamin Eagle Ultra HARLEY DAVIDSON': 26,
 'CafР№ Racer': 27,
 'Chopper': 28,
 'Chopper Soft Tail': 29,
 'Chopper/Bobber': 30,
 'Chopper/bar hopper': 31,
 'City Bike': 32,
 'City X': 33,
 'Classic': 34,
 'Classic Scooter': 35,
 'Commando': 36,
 'Cruiser': 37,
 'Cruiser/Touring': 38,
 'Custom': 39,
 'Custom Chopper': 40,
 'Custom Trike': 41,
 'Deluxe': 42,
 'Dirt Bike': 43,
 'Dual Sport': 44,
 'Dual Sport Adventure': 45,
 'Dual sport': 46,
 'Dual-Purpose': 47,
 'Dual-Purpose Endure dirt bike 250 cc': 48,
 'Dual-Purpose Motorcycle': 49,
 'Dual-Sport': 50,
 'Dyna': 51,
 'ENDURO': 52,
 'Electra Glide Ultra Limited': 53,
 'Enduro': 54,
 'FATBOY': 55,
 'FLHR': 56,
 'FLHRSE вЂ“ CVO Road King with only 280 miles!': 57,
 'FLHXS': 58,
 'FLSTNI': 59,
 'FLSTNI Softail Deluxe': 60,
 'FLSTS Heritage Springer': 61,
 'FREEWHEELER TRICYCLE SPRINGER FRONT 26&#034; WHEEL': 62,
 'FXDB STREET BOB': 63,
 'Factory Custom': 64,
 'Fat Boy': 65,
 'Flat Track Racer': 66,
 'Gasoline': 67,
 'Harley Davidson': 68,
 'Harley Davison': 69,
 'Heritage': 70,
 'Heritage Softail Springer': 71,
 'Iron Head': 72,
 'LIMITED EDITION': 73,
 'Lehman Trike': 74,
 'Limited Edition': 75,
 'Long wheelbase': 76,
 'Lowrider': 77,
 'MINI BIKE': 78,
 'Masterpiece': 79,
 'Mid Engine Rear Wheel Driver': 80,
 'Military': 81,
 'Modern Classic': 82,
 'Moped': 83,
 'Motocross': 84,
 'Motor Scooter': 85,
 'Motorcycle': 86,
 'Motorized Bicycle': 87,
 'Muscle': 88,
 'NINJA': 89,
 'Naked': 90,
 'Naked Sportbike': 91,
 'OFF ROAD': 92,
 'Off-Road': 93,
 'One Owner': 94,
 'Other': 95,
 'PRO STREET': 96,
 'Panhead': 97,
 'Pro Street': 98,
 'R50/2': 99,
 'RACEBIKE': 100,
 'RAT FINK CHOPPER': 101,
 'RAT ROD': 102,
 'ROAD KING': 103,
 'RS 125': 104,
 'Race Bike': 105,
 'Racing': 106,
 'Reverse Trike': 107,
 'Rigid': 108,
 'Road Bike': 109,
 'Road Glide Special': 110,
 'Road King Police Special': 111,
 'Road Scrambler': 112,
 'Road Track Racer': 113,
 'Road king': 114,
 'Rocket': 115,
 'SCOOTER': 116,
 'SHOW BIKE / RIDER': 117,
 'SOFT TAIL CONVERTIBLE CVO 110CI SADDLE BAGS': 118,
 'SOFTAIL': 119,
 'SOFTTAIL': 120,
 'SPRINGER SOFT-TAIL': 121,
 'STREET SCRAMBLER': 122,
 'SUPERBIKE RACER': 123,
 'Scoooter': 124,
 'Scooter': 125,
 'Scrambler': 126,
 'Shovelhead': 127,
 'Show Trike': 128,
 'Silver Jubilee': 129,
 'Slingshot Roadster': 130,
 'Soft tail deluxe cvo': 131,
 'Softail': 132,
 'Softail Springer': 133,
 'Softtail': 134,
 'Sport Bike': 135,
 'Sport Cruiser': 136,
 'Sport Heritage': 137,
 'Sport Touring': 138,
 'Sport Touring-GS': 139,
 'Sportster': 140,
 'Springer': 141,
 'Standard': 142,
 'Standard FXSTI': 143,
 'Street Fighter': 144,
 'Street bike': 145,
 'Street scrambler': 146,
 'Stripe': 147,
 'Super Bike sport bike': 148,
 'Super Mini-Moto': 149,
 'Superbike': 150,
 'Supercharged V-Rod': 151,
 'Supermoto': 152,
 'Supersport': 153,
 'TOURING': 154,
 'TOURING CRUISER': 155,
 'TRAIL': 156,
 'TRI-GLIDE': 157,
 'TRIKE': 158,
 'TRIKE ON AMERICA... RICHLAND ROADSTER TRIKE KIT': 159,
 'Three wheel': 160,
 'Touring': 161,
 'Touring CVO': 162,
 'Touring Road Glide Special FLTRXS': 163,
 'Touring/Sport': 164,
 'Trials': 165,
 'Trike': 166,
 'ULTRA CLASSIC ELECTRA GLIDE CVO': 167,
 'ULTRA TRIKE': 168,
 'Ultra Classic': 169,
 'Upright': 170,
 'V-Star 1300': 171,
 'VW': 172,
 'Vintage': 173,
 'Vintage Dirtbike': 174,
 'Vulcan': 175,
 'Wide Glide': 176,
 'XL883H hugger': 177,
 'all': 178,
 'board track racer': 179,
 'chopper': 180,
 'custom': 181,
 'enduro': 182,
 'fxsts': 183,
 'monkey bike': 184,
 'motorcycle': 185,
 'naked sports bike': 186,
 'scooter': 187,
 'slingshot': 188,
 'sport cruiser': 189,
 'super glide': 190,'super scooter': 191,
 'trike': 192}
        torg = {'False': 0, 'True': 1}
        saler = {'Dealer': 0, 'Other': 1, 'Owner': 2, 'Private Seller': 3}
        damage = {'Clear': 0,
 'Flood, Water Damage': 1,
 'Rebuilt, Rebuildable &amp; Reconstructed': 2,
 'Salvage': 3}
        auction = {'False': 0, 'True': 1}

        data = pd.DataFrame([[condition[variable.get()], float(message1.get()), color[variable1.get()], brands[motor_brand.get()],
                             type[variable2.get()], torg[variable4.get()],saler[variable5.get()],
                             damage[variable6.get()], auction[variable7.get()], float(message2.get())]])
        one_hot = pd.read_csv('one_hot_motor.csv')
        all_data = data.join(one_hot)
        all_data[motor_model.get()] = 1
        print(all_data)
        model = CatBoostRegressor()
        model.load_model('final_motor')
        pred = model.predict(all_data.values)
        Label(carwind, text='Цена: ' + str(round(pred[0])), font=("Arial", 12)).place(x=50, y=200)
        print(pred)




    carwind = Tk()
    carwind.title('moto')
    carwind.geometry('600x270')
    l1 = Label(carwind, text='Год :').place(x=50, y=30)
    l2 = Label(carwind, text='Торг :').place(x=150, y=30)
    l3 = Label(carwind, text='Состояние :').place(x=250, y=30)
    l4 = Label(carwind, text='Цвет :').place(x=350, y=30)
    l5 = Label(carwind, text='Тип :').place(x=450, y=30)
    l6 = Label(carwind, text='Пробег :').place(x=480, y=120)
    l7 = Label(carwind, text='Аукционный? :').place(x=50, y=120)
    l9 = Label(carwind, text='Статус продавца:').place(x=200, y=120)
    l10 = Label(carwind, text='Повреждения:').place(x=350, y=120)
    l11 = Label(carwind, text='Марка:').place(x=200, y=200)
    l12 = Label(carwind, text='Модель:').place(x=350, y=200)

    message1 = StringVar(carwind)
    message2 = StringVar(carwind)

    message_entry1 = Entry(carwind, textvariable=message1).place(x=50, y=60, width=60)#god
    message_entry2 = Entry(carwind, textvariable=message2).place(x=480, y=150, width=60)
    variable = StringVar(carwind)
    opt = OptionMenu(
        carwind, variable, *[
            'New', 'Used'
        ]
    ).place(x = 250, y = 60, width=90)

    variable1 = StringVar(carwind)
    opt = OptionMenu(
        carwind, variable1, *[
             'Black',
             'Red',
             'Blue',
             'White',
             'Silver',
             'Gray',
             'Orange',
             'Green',
             'Burgundy',
             'Yellow',
             'Gold',
             'Vivid Black',
             'Purple',
             'Brown',
        ]
    ).place(x=350, y=60, width=90)

    variable2 = StringVar(carwind)
    opt = OptionMenu(
        carwind, variable2, *[
            'Gasoline',
             'Cruiser',
             'Standard',
             'Touring',
             'Sport Bike',
             'Sport Touring',
             'Dual-Purpose',
             'Off-Road',
             'Naked',
             'CafР№ Racer',
             'Trike',
             'Chopper',
             'Scooter']
    ).place(x=450, y=60, width=90)

    variable4 = StringVar(carwind)
    opt = OptionMenu(
        carwind, variable4, *[
            'True', 'False'
        ]
    ).place(x=150, y=60, width=90)

    variable5 = StringVar(carwind)
    opt = OptionMenu(
        carwind, variable5, *['Dealer', 'Private Seller', 'Owner', 'Other']
    ).place(x=200, y=150, width=90)

    variable6 = StringVar(carwind)
    opt = OptionMenu(
        carwind, variable6, *['Clear',
 'Salvage',
 'Rebuilt, Rebuildable &amp; Reconstructed',
 'Flood, Water Damage']
    ).place(x=350, y=150, width=90)

    variable7 = StringVar(carwind)
    opt = OptionMenu(
        carwind, variable7, *['False', 'True']
    ).place(x=50, y=150, width=90)
    brands = ['Harley-Davidson',
 'Honda',
 'Yamaha',
 'Kawasaki',
 'Suzuki',
 'BMW',
 'Triumph',
 'Ducati',
 'Indian',
 'Other Makes',
 'Can-Am',
 'Custom Built Motorcycles',
 'Victory',
 'Ural',
 'KTM',
 'Campagna',
 'Aprilia',
 'Moto Guzzi',
 'Slingshot',
 'Big Dog',
 'Buell',
 'MV Agusta',
 'Royal Enfield',
 'American Ironhorse',
 'Bourget',
 'BETA',
 'Husqvarna',
 'Polaris',
 'Norton',
 'Bimota',
 'American Classic Motors',
 'Cushman',
 'Hyosung',
 'BSA',
 'Benelli',
 'Piaggio',
 'American IronHorse',
 'Ultimate',
 'Swift Motor Co.',
 'Wild West',
 'ADVANTAGE',
 'Bultaco',
 'Boss Hoss',
 'GMC',
 'Big Bear Choppers']

    models = [['Touring',
  'Softail',
  'Dyna',
  'Sportster',
  'V-ROD',
  'Street Glide',
  'Other',
  'Heritage Softail Classic',
  'Street Glide Special',
  'FLHX - Street Glide',
  'Electra Glide Ultra Classic',
  'Softail Deluxe',
  'Dyna Wide Glide',
  'XL883N - Sportster Iron 883',
  'FXR',
  'Sportster Iron 883',
  'Flhtk Ultra Limited',
  'Softail Fat Boy',
  'Dyna Street Bob',
  'FLHXS - Street Glide Special',
  'Dyna Fat Bob',
  'FLHTK - Ultra Limited',
  'FLHTK ELECTRA GLIDE ULTRA LIMITED',
  'Softail Slim',
  'V-RodВ®',
  'Softail Breakout',
  'Sportster Superlow 883',
  'FLSTF - Softail Fat Boy',
  'Cvo Limited',
  'FLHR - Road King',
  'FLHTKL - Ultra Limited Low',
  'FXDWG - Dyna Wide Glide',
  'Street',
  'Cvo Road King',
  'Xl1200c',
  'FLHTCI',
  'FLHTCU - Electra Glide Ultra Classic',
  'FXDB - Dyna Street Bob',
  'FLHX - Street GlideВ®',
  'Freewheeler',
  'FLSTC - Heritage SoftailВ® Classic',
  'Softail Custom',
  'Night Rod Special',
  'Dyna Switchback',
  'FLSTF FAT BOY',
  'FLTRXS - Road GlideВ® Special',
  'Streetв„ў',
  'XG750 - Street 750',
  'FLHRCI',
  'FLHTCUI',
  'FLTRXS - Road Glide Special',
  'FLSTFB - Softail Fat Boy Lo',
  'XL883C - 883 Custom',
  'FLSTCI',
  'Tri Glide',
  'XL883L - Sportster SuperLow',
  'Electra Glide Standard Police',
  'FLHX',
  'FLHXS - Street GlideВ® Special',
  'Flstfb',
  'FLSTC - Softail Heritage Classic',
  'Sportster Forty-eight',
  'FLHR ROAD KING',
  'Trike',
  'Night Rod Special VRSCDX VRod',
  'FLTRU - Road GlideВ® Ultra',
  'Cvo Ultra Classic Electra Glide',
  'FLTRXS ROAD GLIDE SPECIAL W/ABS',
  'Fltrx - Road Glide',
  'Sportster Seventy-two',
  'V-rod Muscle',
  'Fltrxs - Road Glide Special',
  'Ultra Limited Low',
  'XL1200X - Sportster Forty-Eight',
  'FLSTC - Heritage Softail Classic',
  'FLHRC - Road King Classic',
  'FLHTCU ELECTRA GLIDE ULTRA CLASSIC',
  'FXD',
  'FLTRU ROAD GLIDE ULTRA',
  'Electra Glide Classic',
  'Road Glide',
  'Heritage Classic FLSTC',
  'FXDC - Dyna Super Glide Custom',
  'XL1200X - SportsterВ® Forty-EightВ®',
  'XL1200C - Sportster 1200 Custom',
  'FXSB BREAKOUT',
  'FLRT Free Wheeler',
  'FLSTNI',
  'FLHRC ROAD KING CLASSIC',
  'Street Glide FLHX',
  'street glide',
  'Ultra Classic',
  'FLHTK - Electra GlideВ® Ultra Limited',
  'Electra Glide Standard',
  'FXDLI - Dyna Low Rider',
  'Road Glide Special FLTRXS',
  'Duoglide',
  'FLSTN - SoftailВ® Deluxe',
  'FXDF - Dyna Fat Bob',
  'Road King Classic',
  'FXE',
  'FLHTCUL - Electra Glide Ultra Classic Low',
  'Cvo Road Glide Ultra',
  'FLTRI',
  'Road King',
  'Road Glide Ultra FLTRU',
  'FXDL - DynaВ® Low RiderВ®',
  'FLHRSE4 - Screamin Eagle Road King CVO 105th Anniv',
  'FXDF - DynaВ® Fat Bob',
  'FXRDG . RARE',
  'XL1200 Custom',
  'Ultra Trike Tri Glide FLHTCUTG',
  'Ultra Limited',
  'FLH 1200 Shovelhead',
  'Night Train',
  'Covington Custom FLHX Street Glide',
  'Softail Rocker C',
  'FLSTSE2 - Screamin Eagle Softail Convertible CVO M',
  'Heritage FLST',
  'Road KingВ®',
  'Road Glide Ultra',
  'FXSB - Softail Breakout',
  'Screamin Eagle V-rod',
  'FLHTCUI Electra Glide Ultra Classic Trike',
  'FLHTCUSE8 - CVO Ultra Classic Electra Glide',
  'FLD - DynaВ® Switchbackв„ў',
  'ROAD KING CVO 105th ANNIVERSARY 110 CI',
  'XLCR CAFE RACER',
  'FLHTKSE - CVOв„ў Limited',
  'FXD - DynaВ® Super GlideВ®',
  'Sprint SX',
  'FLHTKSE - Screamin Eagle Limited CVO',
  'FLHTC - Electra GlideВ® Classic',
  'FXSTB - Night Train',
  'Road King Police Special',
  'FLSTS',
  'Vr Destroyer',
  'FLSTF - SoftailВ® Fat BoyВ®',
  'FLTRX',
  'XL883N - SportsterВ® Iron 883в„ў',
  'Flss',
  'FXDI',
  'XL 883N',
  'XL 1200N - Sportster 1200 Nightster',
  'Road Glide Custom',
  'FLHTCU - Electra GlideВ® Ultra ClassicВ®',
  'FLHXSE - Screamin Eagle Street Glide CVO',
  'VRSCA VROD',
  'FLTRX - Road Glide Custom',
  'VRSCF - V-Rod Muscle',
  'AMS',
  'Tri Glide Ultra',
  'Deluxe FLSTN',
  'Vrsc',
  'FLSTS - Heritage Springer',
  'FLSTFSE - Screamin Eagle Fat Boy CVO',
  'XL883 - Sportster 883 Hugger Managers Special',
  'FLTRXS ROAD GLIDE SPECIAL',
  'FLSTSB - Cross Bones', 'FXDWGI - DynaВ® Wide GlideВ®',
  'FLSTFBS - Fat Boy S',
  'FLTRX - Road Glide',
  'FLHXSE - Screamin Eagle CVO Street Glide',
  'FXST - Softail Standard',
  'Sportster 883 Iron',
  'FXDWG - DynaВ® Wide GlideВ®',
  'Insane Custom Cycle',
  'FXSTC - Softail Custom',
  'FLHTK - Electra Glide Ultra Limited',
  'Street Glide Special FLHX',
  'FLHTCU - Ultra ClassicВ® Electra GlideВ®',
  'Switchback',
  'FLSTSI - Heritage Springer',
  'FXSBSE',
  'Dyna Low Rider S',
  'FLSTF - Softail Fat Boy Managers Special',
  'FL',
  'FLHTCU - Electra Glide Ultra Classic Managers Spec',
  'FLSTNSE - CVO Softail Deluxe',
  'FLHRSE5 CVO ROAD KING',
  'XL 1200V',
  'FLTRXS Road Glide Special',
  'FLSTFI',
  'FXCW',
  'Fat Bob',
  'XG750 - StreetВ® 750',
  'Springer Softail',
  'Iron 883',
  'FXDB - DynaВ® Street BobВ®',
  'FLTRU',
  'FXDBI - DYNA STREET BOB',
  'Street GlideР’В® Special',
  'XG500 - Street 500',
  'XL1200T - SuperLowВ® 1200T',
  'Road King Custom by Cam Designs',
  'FLHTP - Electra Glide Police',
  'FLHTCUTG - Tri GlideВ® Ultra ClassicВ®',
  'FLHTCUSE3 - Ultra Classic Screamin Eagle Anniversa',
  'FXSTC',
  'FXRS - Low Glide',
  'FXDCI',
  'FXDWG',
  'FXLR - Low Rider Managers Special',
  'FLHTC - Electra Glide Classic Managers Special',
  'SportsterР’В®',
  'FLHRCI - Road KingВ® Classic',
  'XG750',
  'FLRT - Freewheeler Trike',
  'FLHXS STREET GLIDE SPECIAL W/ABS',
  'VRSC',
  'FLHTCU - Ultra Classic Electra Glide',
  'VRSCF - V-Rod MuscleВ®',
  'FXDL',
  'Street Glide Special FLHXS',
  'FLHX-103 Street Glide',
  'FLSTCI - Heritage Softail Classic Managers Special',
  'FLSTC Heritage Softail Classic',
  'SPORTSTER 1200',
  'Vrscse Screamin Eagle V-rod',
  'FLSTFB - SoftailВ® Fat BoyВ® Lo',
  'FLHTK',
  'V-RodР’В®',
  'XL883',
  'ULTRA CLASSIC',
  'FXDF - Dyna Fat Bob Trike',
  'FLHTCUTG TRIGLIDE ULTRA CLASSIC',
  'FXDBI - Dyna Street Bob Managers Special',
  'FXSB - SoftailВ® BreakoutВ®',
  'XL883C',
  'FLTRX - Road GlideВ®',
  'FLHR Road King',
  'Fat Boy',
  'FLHR - Road King Managers Special',
  'Electra Glide Ultra Limited',
  'FLHRSEI2 - Screamin Eagle Road King Managers Speci',
  'FLHTCUSE CVO ELECTRA GLIDE ULTRA CLASSIC',
  'WLC 45 stroker',
  'FLD103',
  'Softail Deluxe(FLSTNI)',
  'XL1200R Roadster',
  'Low Rider',
  'FLSTF FAT BOY W/ABS',
  'Pro One California',
  'CVO Breakout',
  'FXDWG - Wide GlideВ®',
  'FLHTKSE CVO ULTRA LIMITED',
  'STREET GLIDE SPECIAL (FLHXS)',
  'Flhri Road King',
  'FREEWHEELER SPRINGER TRIKE TRICYCLE TRI CYCLE',
  'Dyna Glide Fat Bob FXDF',
  'XL 883C',
  'Cvo Softail Deluxe',
  'FLHR - Road King Peace Officer Edition Managers Sp',
  'FXSTB - Night Trainв„ў',
  'XL883L - Sportster 833 Low Managers Special',
  'FLHRI - Road King Trike',
  'FXDLI - Dyna Glide Low Rider',
  'FLHTC ELECTRA GLIDE CLASSIC',
  'VRSCB - V-Rod Managers Special',
  'tri gilde',
  'FXDI - Dyna Super Glide',
  'Streetbob',
  'FLHTCUTG - Tri Glide Ultra Classic Trike',
  'XL1200X - Sportster Forty-Eight Managers Special',
  'FLHRI ROAD KING',
  'FXDF',
  'FXDSE - Screamin Eagle Dyna CVO',
  'ELECTRA GLIDE',
  'FLHTCUI Electra Glide Ultra Classic Anniversary',
  'Electra Glide',
  'Tri Glide Ultra Classic',
  'XL1200C - Sportster 1200 Custom - Managers Special',
  'FLTRUSE - Screamin Eagle Road Glide Ultra CVO',
  'FLHXSE - CVOв„ў Street GlideВ®',
  'XL1200V - Sportster Seventy-Two Managers Special',
  'FLHXS STREET GLIDE SPECIAL',
  'FLHTCUSE3 - Screamin Eagle Ultra Classic Anniversa',
  'FXDFSE2 - Screamin Eagle Fat Bob CVO',
  'Screamin Eagle Limited  CVO FLHTKSE',
  'FLSTN - Softtail Deluxe',
  'XL1200X  Forty-Eight',
  'ROAD KING CLASSIC',
  'FXS BLACKLINE W/ABS',
  'FLHX - STREET GLIDE',
  'XLCH Sportster',
  'FLHTCU',
  'FXSB - BreakoutВ®',
  'FLSTC - Heritage Softail Classic Managers Special',
  'Custom',
  'FLSS - SoftailВ® SlimВ® S',
  'Softail Deuce',
  'FLSTN',
  'Cvo Road Glide',
  'Road GlideР’В®',
  'Electra GlideР’В® Ultra Limited FLHTK',
  'PANHEAD',
  'FLHTCUSE2 SCREAMIN EAGLE ELECTRA GLIDE ULTRA CLASS',
  'Softail Rocker',
  'FLHP - Road KingВ®', 'FXSTSSE - Screamin Eagle Softail Springer CVO',
  'Cvo Fat Boy',
  'Street 750',
  'XL 883L',
  'VRSCA - V-Rod',
  'Ultra Tri Glide',
  'Harley Davidson',
  'FLHR - Road KingВ®',
  'XL1200V - Sportster Seventy-Two',
  '2013 Harley Davidson Road King FLHR',
  'FLSTC',
  'Electra Glide Ultra Classic Low',
  'FLHXI',
  'FXDSE2 - DynaВ® Screamin&#039; Eagle Anniversary',
  'FLD - Dyna Switchback',
  'FLHTCUI - Ultra Classic Electra Glide',
  'FXDL - Dyna Low Rider Managers Special',
  'FLHXSE2 - Screamin Eagle CVO Street Glide',
  'Sportster Superlow 1200t',
  'FLHTC',
  'FLTRXSE2 - Screamin Eagle CVO Road Glide Custom',
  'FXSB BREAKOUT W/ABS',
  'FLHTK - ELECTRA GLID',
  'XL1200X - Forty-Eight',
  'XL883N - Sportster Iron 883 Managers Special',
  'SOFTAIL CVO CONVERTIBLE 110 SIDE BAGS',
  'FLH Duo-Glide',
  'Roadster',
  'XL1200T - SportsterВ® SuperLowВ® 1200T',
  'FLHXSE - CVO Street Glide',
  'FLHRC - Road KingВ® Classic 105Th Anniversary Edit',
  'ROADGLIDE',
  'FLSTF Fat Boy',
  'FXRC - Low Glide Custom',
  'XL1200L - SportsterВ® 1200 Low',
  'FLRT - Freewheelerв„ў',
  'Shovelhead/rigid',
  'XL1200CX - Roadster',
  'Cvo Softail Convertible',
  'FLHTCUSE3 - Screamin Eagle Ultra Classic CVO',
  'FLSTFSE - Softail Fat Boy Screamin Eagle',
  'XL1200 48&#039;',
  'FLS - Softail Slim',
  'FXCWC - Rocker C Managers Special',
  'FXSTDI',
  'flhxse',
  'FXD - Dyna Super Glide',
  'FLRT TRIKE',
  'FXDBI',
  'FLHTCU - Ultra Classic Electra Glide  STRETCHED BA',
  'XL883 SuperLow',
  'FLRT - Freewheeler',
  'FLH',
  'FLSTCI - Heritage Softail Classic Trike',
  'FLHTCUI - Ultra ClassicВ® Electra GlideВ®',
  'FXDI35 - Dyna 35th Anniversary Super Glide',
  'FXSE CVO PRO STREET BREAKOUT',
  'V-Rod Muscle',
  'Dyna Super Glide',
  'FLTRX - Road GlideВ® Custom',
  'XL883L - SuperLow',
  'Fxse',
  'VRSCA VROD 100TH ANNIVERSARY',
  'FLSTFB - FAT BOb',
  'FLHTCUTG - Tri GlideВ® Ultra',
  'FLHX STREET GLIDE',
  'FLHTKL',
  'FLHRC - Road KingВ® Classic',
  'VRSCAW - V-Rod',
  'XG500 - Streetв„ў 500',
  'FLHT - Electra GlideВ® Standard',
  'FLHTCUI ULTRA GLIDE ELECTRA GLIDE ANNIVERSARY',
  'FLHRSI',
  'Custom Road Glide',
  'FXSB - Breakout',
  'FXSTSB - Bad Boy Softail Springer'],
 ['Gold Wing',
  'CB',
  'CBR',
  'Shadow',
  'Other',
  'CRF',
  'VTX',
  'CT',
  'Interceptor',
  'Fury',
  'CR',
  'Valkyrie',
  'XR',
  'CL',
  'Rebel',
  'CBRВ® 600RR',
  'CA',
  'Magna',
  'CTX700N',
  'CTX 700N',
  'CBR500R',
  'CBX',
  'Touring',
  'Vt13ctb',
  'ShadowВ® Spirit 750',
  'Elite',
  'RC51',
  'VTX 1300 C',
  'CBR 250R Repsol Edition Managers Special',
  'XL',
  'VFR1200X',
  'FT 500',
  'Gold Wing Valkyrie GL1500CD',
  'NC700X',
  'VFR400R',
  'ST-90',
  'XL250R',
  'Interstate',
  'Gold Wing F6BВ®',
  'Sabre',
  'Forza',
  'CX 500 Delux',
  'Shadow AeroВ®',
  'GoldWing Interstate',
  'ST1300 POLICE ABS EXCELLENT',
  'CBR600RR',
  'CBR1000RR',
  'Sabre VT1100C2',
  'ST1300',
  'shadow',
  'Stateline',
  'Africa Twin',
  'CBR650F',
  'GL500',
  'NT700V',
  'MR50',
  'CB750 chopper',
  'VTX1300S',
  'CM91',
  'VTXв„ў 1300 C',
  'Magna V65',
  'GOLDWING TRIKE',
  'ReflexВ®',
  'XL75',
  'Nx 125',
  'Goldwing',
  'CRF 450R',
  'ShadowВ® Aero',
  'Grom',
  'NSX JDM RHD Midnight Purple Pearl 100% Fed Legal',
  'NT700VВ®',
  'VTX1300',
  'Helix 250',
  'Honda',
  'VTX1300C',
  'VTX 1800C Spec 1 Managers Special',
  'GROM',
  'VTR1000F',
  'GL1800 GOLDWING 1800 W/COMFORT',
  'GL1500 GOLDWING 1500 MOTOR TRIKE',
  'Cb750k',
  'CRF250L',
  'Nighthawk 250 Managers Special',
  'CB500T',
  'GL 1500 Gold Wing',
  'CTX1300',
  'Gold Wing F6B GL1800B',
  'PCX 150',
  'FT500',
  'CT200 Trail 90',
  'ST1300PA',
  'VTX1800C2',
  'GL 1500 Gold Wing Aspencade',
  'INTERSTATE 1300',
  'Nc700jdg',
  'VTXв„ў 1300 R',
  'CBR500R W/ABS',
  'Pacific Coast',
  'CRF450R',
  'VTX 1300 R',
  'Nighthawk',
  'ShadowВ® Sabreв„ў',
  '650L',
  'ST1100',
  'GL1500CTX',
  'Helix CN250',
  'Interstate VT 1300 Touring Silver Cruiser',
  'NC700X DCT ABS',
  'PC800 PACIFIC COAST',
  'GL1500 VALKYRIE 1500 INTERSTATE',
  'Gold Wing GL18003 with Trailer',
  'NT700VA',
  'Shadow Aero','VTX1300R',
  'CRB',
  'VTXв„ў 1300 Tourer',
  'StatelineВ®',
  'VTX 1800 S',
  'Reflex',
  'Super Hawk',
  'CBRВ® 1000RR',
  'CX500C',
  'CRF150R',
  'VFR',
  'mini trail',
  'C100',
  'CM450E',
  'Hawk',
  'Rebel500 CMX500',
  'st1300',
  'VTX 1800R Spec 3',
  'Shadow Spirit 750 VT750C',
  'VTX 1300 S Managers Special',
  'VTX1800C'],
 ['V Star',
  'YZF-R',
  'FZ',
  'YZ',
  'FJR',
  'YZF',
  'V Max',
  'Raider',
  'Stryker',
  'XS',
  'Road Star',
  'Stratoliner',
  'Other',
  'XT',
  'Bolt',
  'FZ-09',
  'YZF-R6',
  'YZF-R1',
  'V Star 1100 Classic XVS1100A',
  'Big Wheel',
  'Zuma',
  'R6',
  'XSR900',
  'XVS1300 VSTAR 1300',
  'SR400',
  'XVS650 VSTAR 650 CLASSIC',
  'YZFR6 600',
  'Royal Star',
  'Vino',
  'XV1700',
  'WR',
  'Roadliner',
  'FJ09 900',
  'DT250',
  'FJR1300A',
  'V Star 1300 Tourer',
  'WR250R',
  'PW',
  'Royal Star Midnight Venture',
  'RZ350',
  'FZ-07 ABS',
  'RD350',
  'FJR 1300AE YCC-S ABS Managers Special',
  'roadstar',
  'TT-R',
  'IT250',
  'YZFR1 1000',
  'Royal Star Venture',
  'Super TР“В©nР“В©rР“В©',
  'R1 ',
  'Fz8',
  'r1z',
  'FZ-10',
  'wr250r',
  'V STAR 950',
  'Fjr13sdl',
  'XT250',
  'YFM700 GRIZZLY 700',
  'STRYKER',
  'ZUMA',
  'FZ6R Two Tone',
  'VMAXВ®',
  'Stratoliner Deluxe - XV19CTFER',
  'Royal Star Midnight Venture XVZ13TFMT',
  'FJ09 900 W/ABS',
  'DT1MX 250',
  'V Star 1100 Classic - XVS11AWYG Managers Special',
  'V STAR 1300 Tourer',
  'TY175',
  'Dt360',
  'YZF R6',
  'Super TenereВ®',
  'TTR 230',
  'V Star 1100 Custom - XVS1100XB Managers Special',
  'YXR700 RHINO 4X4',
  'R1',
  'V STAR 1300 TOUR',
  'STRYKER 1300  XVS13CAO/C',
  'FZ1 1000',
  'Star Bolt',
  'YZF-R1 Raven/Candy Red',
  'TW 200EC',
  'V STAR 650',
  'V Star 1300 XVS1300',
  'RD400F',
  'YM1',
  'YFZ-450',
  'Venture Royale',
  'ROAD STAR XV1600',
  'Super Tenere',
  'V StarВ® 1300 Tourer',
  'V StarВ® 1300 Deluxe',
  'R3',
  'Roadliner Midnight - XV19MY',
  'YSR50',
  'YZFR1 1000 W/ABS',
  'Virago',
  'XVS1300',
  'SCR 950',
  'vision 550',
  'SMAX',
  'TT',
  'YZ250FX',
  'V Star 1300 Tourer - XVS13CTXB',
  'FJR1300',
  'Roadstar',
  'V-Star 1100 Custom',
  'V Star 950 - XVS95BR Managers Special',
  'Yzf-r1 Team Yamaha',
  'Tw200',
  'FJ 1200',
  'V-STAR 1300 Tourer',
  'DT Enduro',
  'Road Star Silverado',
  'SCR950',
  'RD400',
  'FZ 6',
  'VMX12',
  'Star',
  'V Star 650 Custom',
  'FJ-09',
  'ttr230',
  'WR 250 F',
  'AT3',
  'FJ-09 ABS',
  'V Star 1100 Classic XVS11AW',
  'Royal Star Tour Deluxe'],
 ['Ninja',
  'Vulcan',
  'KX',
  'KLR',
  'Versysв„ў',
  'Other',
  'KLX',
  'ZG1400 CONCOURS 1400 W/ABS',
  'KZ',
  'Concoursв„ў',
  'ZX-6R',
  'Z650',
  'Concours 14',
  'LTD 1000',
  'Versys',
  'VulcanВ® 900 Classic',
  'Z1000 ABS',
  'Z900',
  'ZR800 Z800 W/ABS',
  'ZX14R NINJA 1400 W/ABS',
  'kz1300',
  'Versys 1000 LT Sport Touring',
  'NinjaВ® ZXв„ў -14R ABS',
  'NinjaВ® ZXв„ў-14R ABS',
  'ZX1000',
  'ZX14R NINJA 1400 SPECIAL EDITION',
  'VERSYS 1000LT',
  'Concours',
  'ZX1000 NINJA 1000',
  'ZRX 1200R',
  'KLR650',
  'Z 125 Pro',
  'ZX-14R ABS',
  'KLE650 VERSYS W/ABS',
  'Vulcan 900 Custom Bobber',
  'ZВ®',
  'Ninja ZXв„ў-6R',
  'Z800 Naked Sport',
  'Vulcan 1700 Voyager - VN1700A',
  'H2',
  'Kawasaki',
  'ZX14 SPECIAL EDITION',
  'VulcanВ® 1500 Nomadв„ў',
  'Concours 14 ABS',
  'Vulcan 900 Classic VN900B',
  'VulcanВ® 1700 Classic LT',
  'Concours 14 ABS ZG1400EHF',
  'Concoursв„ў 14 ABS',
  'Versys 650 ABS',
  'CONCOURSE 14',
  'Ninja ZXв„ў-10R',
  'KZ400 Special',
  'Versys 650 - KLE650A Managers Special',
  'Ninja 250R EX250R',
  'KXF',
  'Ninja 250R Managers Special',
  'KLR 650 Managers Special',
  'Vulcan 1700 Nomad ABS - VN1700D',
  'KX450HHF',
  'ZX-10R',
  'Vulcan 900 Custom - VN900C',
  'ZG1000A9',
  'Vulcan 2000 Classic LT VN2000J',
  'Vulcan 1700 Nomad - VN1700C Managers Special',
  'VULCAN 1700 VAQUERO',
  'Vn900d6f',
  'Vulcan 1700 Voyager ABS VN1700BC',
  'ZG 1200',
  'NinjaВ® ZXв„ў -6R',
  'Z1A',
  'NinjaВ® ZXв„ў -10R ABS',
  'Versys 650 LT',
  'Vulcan 2000 - VN2000A Managers Special',
  'Versys 650 Sport Touring',
  'Vulcan 1600 Nomad VN1600D','Vulcan 900 Classic',
  'ZL600',
  'VERSYS ABS',
  'Z1000',
  'VERSYS-X 300',
  'NinjaВ® ZXв„ў-6R ABS',
  'Vulcan 900 Custom',
  'z125 Pro',
  'ZX-12R',
  'KZ1100',
  'Z1R',
  'Ex300 Ninja 300',
  'KLE650FHFL',
  'Z1000 G',
  'KLE650',
  'VulcanВ® S ABS'],
 ['Boulevard',
  'GSX-R',
  'Hayabusa',
  'Other',
  'SV',
  'GS',
  'GSX / Katana',
  'GSX-R750',
  'V-Strom 650',
  'GSXR750',
  'Intruder',
  'Bandit',
  'V-Strom',
  'GSX-Rв„ў 1000',
  'GSX-Rв„ў 600',
  'GSX-R600',
  'Marauder',
  'Burgman 650',
  'DL1000',
  'GSX-R 750',
  'C50bk7 Boulevard',
  'B-King',
  'GSX-S750',
  '550 GSL',
  'TS250',
  'GSX1300R',
  'DL650 VSTROM 650 W/ABS',
  'GSX-S750Z',
  'V-strom',
  'gw250',
  'GSX1250FA W/ABS',
  'Hayabusaв„ў 1300R',
  'AN650',
  'Boulevard S50',
  'GT185',
  'Gsxr1300',
  'SV 650SF',
  'DL650',
  'C109R Boulevard',
  'DL 650 V-Strom',
  'Boulevard C90T',
  'Vs 800 Intruder',
  'GZ250',
  'GSX 1300RAZL4',
  'Boulevard C90T B.O.S.S.',
  'GW',
  'Vstrom',
  'AN650 BURGMAN 650 EXECUTIVE W/ABS',
  'GSX-S1000',
  'Sv650sfk9',
  'Burgman 400',
  'GSX-R 600',
  'GSXв„ў R600',
  'TC100',
  'C90T BOSS',
  'DR-Z',
  'Intruder 1400',
  'C50 T',
  'DR200 SL5',
  'Cavalcade LX Managers Special',
  'V-Strom 1000 ABS',
  'GS500E',
  'SV650',
  'suzuki',
  'GSX600 KATANA',
  'GSX-S 750',
  '1250 FA',
  'M109r',
  'Boulevard C50 Trike',
  'SUZUKI GW250F',
  'ls650 boulevard',
  'GSXR1000',
  'TL1000R',
  'Boulevard C50 T Classic',
  'Burgman 400 Managers Special',
  'TC 100',
  'Boulevard C50 VL800',
  'RE5',
  'RM-Z250',
  'GSX-R1000',
  'Burgman',
  'GSX1300RA',
  'Hayabusa 1300R',
  'RMZ250',
  'V-STROM DL650A 650 ABS',
  'Sp250',
  'RM',
  'GSX-R750в„ў',
  'GS550T'],
 ['R-Series',
  'K-Series',
  'F-Series',
  'Other',
  'K1600GT',
  'R 1200 R Premium Cordoba Blue',
  'G650GS',
  'F800R',
  'F800ST',
  'S 1000 R Premium Light White/Lupin Blue Metallic/R',
  'Custom R nineT',
  'S1000RR',
  'S 1000 RR Premium Race LightWhite/LupinBlueMet/Rac',
  'K1600GTL',
  'K1600GTL PREMIUM W/ABS &amp; ESA',
  'K 1600 GTL Thunder Grey Metallic Premium Pack',
  'S 1000 R',
  'R 1200 R',
  'R 1150 RT',
  'K 1600 B Black Storm Metallic Touring &amp; Safety Pac',
  'GS 1200',
  'S 1000 RR',
  'F 800 GT Premium Light White',
  'S 1000 RR Standard Race GraniteGreyMetallic/BlackS',
  'F800',
  'R1150RT W/ABS',
  'R1200ST',
  'K1300GT PREMIUM W/ABS',
  'G 650 GS Premium Aura White with Black / Grey Seat',
  'c650gt',
  'K1300GT PREMIUM W/ABS &amp; ESA',
  'S 1000 RR Race Racing Red/Light White',
  'G 650 GS Premium Deep Black with Black / Grey Seat',
  'R1200GS',
  'R1200RT POLICE'],
 ['Bonneville',
  'Thunderbird',
  'Tiger',
  'Daytona',
  'Street Triple',
  'THRUXTON',
  'Street Cup',
  'STREET TWIN W/ABS',
  'Rocket III',
  'America',
  'Sprint',
  'THRUXTON R',
  'Speed Triple',
  'Trophy',
  'Bonneville T100 Fusion White/Aegean Blue',
  'Other',
  'Street Twin Matte Jet Black',
  'Tiger Explorer ABS',
  'Trident',
  'Tiger Explorer XCX CrystalВ\xa0White',
  'Bonneville T100 Black Matte Black',
  'Speedmaster',
  'Daytona 675 R ABS Matte Phantom Black/Matte Alumin',
  'Tiger 800 XR',
  'Scrambler',
  'Legend',
  'Thruxton 1200 Competition Green',
  'Street Twin',
  'Daytona 675 R ABS Eslick Spec Ed',
  'Street',
  'Tiger 1050',
  'Tiger Explorer Xc',
  'Sprint ST ABS',
  'Street Scrambler',
  'Tiger 800 XRX Crystal White',
  'Thunderbird LT ABS Lava Red / Phantom Black',
  'Bonneville T100 Black Jet Black',
  'Scrambler 2 Tone',
  'Trophy SE  ABS Phantom Black',
  'Speedmaster Matte',
  'Tiger Explorer XRT CrystalВ\xa0White',
  'Street Scrambler Jet Black',
  'Trophy SE  ABS Pacific Blue',
  'Tiger 800 XC',
  'Bonneville T120 Aluminium Silver',
  'Street Triple R Matte Aluminium Silver',
  'Tiger 800 XCA Crystal White',
  'Thruxton 1200',
  'Street Scrambler Korosi Red / Frozen Silver',
  'Speed Triple R ABS Crystal White',
  'Tiger Explorer Standard',
  'Tiger 800 XRT',
  'THRUXTON 1200 R',
  'Speed Triple R (ABS)',
  'Thruxton 1200 R Matte Jet Black',
  'Thruxton 1200 R',
  'Thunderbird Storm',
  'Thruxton 900',
  'Speed Four','Daytona 675',
  'Tiger 800 XCX Crystal White',
  'Thruxton Standard',
  'SPEED 4',
  'Bonneville T120 Jet Black Pure White',
  'Street Triple R Jet Black',
  'America LT',
  'Rocket III Roadster ABS Matte Phantom Black w/ Twi',
  'Tiger Explorer XC ABS',
  'Bonneville Bobber Ironstone',
  'Thunderbird Sport',
  'Street Triple R Crystal White Metallic'],
 ['Superbike',
  'Monster',
  'Multistrada',
  'Diavel',
  'Other',
  'Supersport',
  'Sport Touring',
  'Hypermotard',
  'Bevel drive',
  '848 EVO',
  'Monster 821 Red',
  'HYPERSTRADA W/ABS &amp; DTC',
  'Multistrada 1200 Enduro Phantom Grey',
  'Monster 1200 S Red',
  'XDIAVEL',
  'Multistrada 1200 S Touring',
  'Multistrada 1200',
  'Scrambler Flat Track Pro',
  'Scrambler',
  '888 Corsa Factory Ducati Racing Superbike',
  'Monster 797 Ducati Red',
  'XDiavel S Thrilling Black',
  'Monster 1200 R Thrilling Black',
  'SCRAMBLER ICON',
  'Xdiavel',
  'Multistrada 1200 Enduro Red',
  'Multistrada 1200 S Touring Edition',
  '750 SPORT',
  'Multistrada 1200 Touring Package',
  'Diavel Carbon White',
  'Panigale 959',
  '959 Panigale',
  '1299 Panigale S',
  'Multistrada 1200 S Volcano Grey',
  'Multistrada 950 Red',
  'Scrambler Sixty2 Shining Black',
  'Diavel Red Carbon',
  'Hypermotard 1100 EVO SP',
  '959 Panigale Arctic white silk',
  '750 Paso',
  'Superbike 1199 Panigale S',
  '250 Desmo Silver Shotgun',
  'Diavel Strada',
  'DIAVEL',
  '999',
  'SCRAMBLER CLASSIC',
  'Monster 1200 S Star White',
  'ST3',
  'Scrambler Icon Ducati Red',
  '1299 Panigale',
  '1199 Superleggera',
  'Multistrada 1200 S Pikes Peak',
  'Sport Classic',
  'HyperMotard SP',
  'Multistrada 950 Star White Silk',
  '966 S',
  'Monster S2R Managers Special',
  'Diavel Carbon',
  'Darmah SD900'],
 ['Chief',
  'RoadmasterВ®',
  'Scout',
  'ChieftainВ®',
  'Springfield',
  'ScoutВ®',
  'ChiefВ® Vintage',
  'Roadmaster',
  'ChieftainВ® Limited',
  'Springfieldв„ў',
  'Chief Vintage Thunder Black',
  'Chief Dark HorseВ® Thunder Black Smoke',
  'Chieftain Dark HorseВ®',
  'SPRINGFIELD INDIAN RED',
  'Springfield Indian Motorcycle Red',
  'INDIAN CHIEF DELUXE',
  'RoadmasterВ® Burgundy Metallic',
  'Cheif Vintage',
  'Indian',
  'Chief Dark HorseВ®',
  'Chieftain',
  'Chief Vintage Thunder Black BLOWOUT PRICING CALL T',
  'Springfield Thunder Black BLOWOUT PRICING CALL TOD',
  'Scout Sixty ABS',
  'Chieftain Limited Wildfire Red over Thunder Black',
  'Roadmaster Thunder Black BLOWOUT PRICING CALL TODA',
  'RoadmasterВ® Classic Thunder Black',
  'Indian Chieftain',
  'ChieftainВ® Silver Smoke',
  'ChiefВ® Vintage Jack Daniel&#039;sВ® Limited Edition',
  'woodsman',
  'ScoutВ® Sixty ABS',
  '249',
  'Scout Bobber ABS',
  'Scout Sixty',
  'CHIEFTAIN',
  'ChiefР’В® Vintage',
  'Chief Vintage Indian Motorcycle Red',
  'Roadmaster Managers Special',
  'Chief Vintage Indian Red',
  'Scout Sixty Pearl White',
  'ScoutВ® Sixty',
  'Roadmaster Classic',
  'Scout Sixty Thunder Black',
  'ChieftainВ® Limited Wildfire Red over Thunder Black',
  'Chief Dark Horse Thunder Black Smoke BLOWOUT PRICI',
  'Chief Vintage Springfield Blue',
  'Chief Dark Horse',
  'ScoutВ® ABS',
  'Chieftain Limited',
  'ChiefВ® Classic Pearl White',
  'Indian Sport Scout 640',
  'RoadmasterВ® Classic',
  'Chief Vintage',
  'Chief Classic CALL FOR INTERNET PRICING TODAY',
  'ChiefВ® Classic',
  'ChiefВ® Vintage Indian Red / Thunder Black',
  'FOUR',
  'ScoutВ® Sixty Thunder Black'],
 ['Enduro HAWK 250CC ( Free shipping to your door)',
  'Slingshot SL',
  'SLINGSHOT SL',
  'Matrix',
  'Slingshot',
  'PIAGIO MP3',
  'ICE BEAR',
  'WC1',
  'slingshot',
  '2017 Polaris Slingshot SL LE',
  'Patriot Phantom',
  'Mead Ranger',
  'SLINGSHOTВ®',
  'GTS 250 IE',
  'Moto-Scoot',
  'K1200',
  'DB 201',
  'SLINGSHOT',
  'MX Z TNT 800R ETEC',
  'Matchless G85CS',
  'Razkull 125',
  'VB150',
  'HAWK',
  'ORANGE COUNTY CHOPPERS ORIGINAL',
  '2017 Polaris Slingshot SL',
  'Custom Built',
  'Polaris Slingshot SL',
  '007 dirt bike',
  'Buell m2 cuclone',
  'Vintage American Moto Scoot',
  'Enduro Magician 250 (Free shipping to your door)','Arlen Ness Ultra Custom',
  'cr125',
  'RIGID CHOPPER',
  'Custom',
  'APOLLO DIRT BIKE 250',
  '450 EFI',
  'ET4',
  'Polaris Slingshot',
  'SLR',
  'Super X',
  'Can Am',
  'Slingshot SLR',
  'American Eagle Maverick Custom',
  'Genuine hooligan 170i',
  'SPYDER RS-S',
  'American GT',
  'SLR Orange Madness',
  'Hawk 250',
  'SPORTSMAN 570 TOURING EFI',
  'LIFER',
  'Motoped Cruzer',
  'Dongfang 250 rtd',
  'Chopper',
  'BAJAJ CHETAK',
  '2017 Polaris Slingshot SLR',
  'Genuine Blur 220i',
  'MT16',
  'VZR1800'],
 ['Spyder RT-S',
  'Spyder RT',
  'Spyder',
  'Spyder F3',
  'SPYDER',
  'Spyder F3-T SE6',
  'Spyder F3 Limited',
  'SPYDER F3-T SE6',
  'RT',
  'Spyder RT Limited',
  'SPYDER RT-S SE6',
  'F3-S',
  'Spyder RS-S SE5',
  'RSS',
  'Spyder Roadster RS',
  'Spyder F3-T Limited Special Series',
  'Spyder RT-S SE6',
  'SPYDER F3 LIMITED',
  'Spyder RS-S',
  'Spyder F3 SM6',
  'Spyder RS',
  'SPYDER F3 LIMITED - Demo',
  'SpyderВ® F3 S 6-Speed Semi-Automatic (SE6)',
  'SPYDER RS SPECIAL EDITION',
  'ST-S',
  'ST',
  'SpyderВ® F3 S 6-Speed Manual (SM6)',
  'RS-S SE5',
  'Spyder RT-S SM5',
  'Spyder ST',
  'SPYDER RS-S SM5',
  'SPYDER F3-S',
  'CAN AM SPYDER RT',
  'SPYDER ST LTD',
  'Spyder RTS',
  'Spyder F3 SE6',
  'Spyder ST-S',
  'SPYDER RS-S SE5',
  'Spyder Roadster RS-S',
  'F3 Limited'],
 ['Chopper',
  'Bobber',
  'Pro Street',
  'Other',
  'Cafe Racer',
  'street glide',
  'Johnny Pag',
  'DKCC Trike',
  'Cyclone Board Track Racer',
  'RF-1 LT2',
  'Sportsman Flyer',
  'VW Trike',
  '1200 Nightster',
  'V8 CHOPPERS TRIKE HR NLY 7700 MI',
  'trike'],
 ['Cross Country',
  'VEGAS',
  'Vision Tour',
  'Vegas',
  'Magnum',
  'Cross CountryВ® Tour',
  'SPORT CRUISER',
  'Magnumв„ў',
  'Vegas Arlen Ness Signature Series',
  'vegas jackpot',
  'HAMMER 8 BALL',
  'Hammerв„ў',
  'Octane',
  'VegasВ®',
  'High Ball',
  'Visionв„ў',
  'Vegas 8-Ball',
  'High-Ballв„ў',
  'jackpot',
  'JackpotВ®',
  'Cross Country Tour Bronze Mist',
  'Judgeв„ў Suede Nuclear Sunset',
  'Cross Road',
  'Judge',
  'Hammer',
  'Cross Roads Classic LE',
  'JACKPOT PREMIUM EXTREME GRAPHICS',
  'Cross Country Cory Ness',
  'Cross Country Suede White Frost',
  'Cross Country Tour',
  'Hard-Ball ABS',
  'Cross Countryв„ў',
  'CROSS ROADS',
  'JACKPOT',
  'Cross Roadsв„ў',
  'Vision',
  'Jackpot',
  'Vegas 8 Ball',
  'Octane Matte Super Steel Gray',
  'Vegas Jackpot',
  'Other',
  'Octaneв„ў'],
 ['Gear-Up',
  'Gear Up (2WD)',
  'Solo sT',
  'cT',
  'Gear Up 2WD Maroon Custom',
  'Retro Classic Black Gloss',
  'Patrol 2WD Grey Metallic',
  'Gear Up 2WD Forest Fog Custom',
  'Patrol 2WD Burgundy Metallic',
  'Gear Up 2WD Flat Black Custom',
  'Patrol',
  'Gear Up 2WD Cascade Green',
  'Gear Up 2WD Taiga Custom',
  'Limited Edition Ambassador Plus',
  'Retro Classic Orbital White',
  'Gear Up 2WD Woodland Custom',
  'cT Terracotta',
  'Solo',
  'Gear Up 2WD Sahara Custom',
  'Gear Up',
  'M70 Forest Fog Custom',
  'Gear Up 2WD Asphalt Custom',
  'Gear Up 2WD Asphalt',
  'Patrol (2WD) - CUSTOM',
  'M70 Maroon Custom',
  'Gear Up 2WD Urban Camouflage Custom',
  'Gear Up 2WD Military Green',
  'M70 Flat Black Custom',
  'cT Terracotta Custom'],
 ['SX',
  'EXC',
  'Adventure',
  '1290 SUPER DUKE GT',
  '250 SX-F',
  '690 DUKE',
  '250 XC-W XCW',
  'superduke r',
  'RC8 1190',
  '690 SM',
  '1290 Super Duke R',
  '300 XC-W',
  '1190 RC8R',
  'RC8r',
  '350SXF',
  '390',
  '450 EXC-F SIX DAYS'],
 ['T-Rex', 'Trex14r', '16sp', 'T-rex', 'Trex', 'V13R'],
 ['Caponord',
  'SCARABEO 500',
  'APRILIA RSV4 RF NO FEES, FREE SHIPPING!',
  'Tuono',
  'RS125',
  'RSV4R APRC',
  '2017 Tuono 1100 RR, NO FEES, FREE SHIPPING!',
  'RSV1000R FACTORY',
  'SL1000R',
  '2017 Tuono Factory, NO FEES, FREE SHIPPING!',
  'NEW 2016 APRILIA CAPONORD RALLY ABS, WE SHIP!!',
  'rsv1000r',
  'Caponord 1200 ABS Travel Pack',
  'TUONO 1000',
  'Futura',
  'Scarabeo',
  'Tuono V4 1100 RR',
  'RS50'],
 ['V9',
  'Eldorado',
  'Audace',
  'Griso',
  'CALIFORNIA 1400',
  'V9 Roamer',
  'Lemans V',
  'V65 TT',
  'SPNT1000',
  'MGX-21',
  'V7 II',
  'Breva 750 I.E.',
  'Jackal',
  'Nevada','California',
  'Breva V 1100',
  'Stelvio',
  '1100 Sport'],
 ['Slingshot SLR', 'Slingshot SL', 'Slingshot', 'Slingshot SL LE'],
 ['K9',
  'Mastiff',
  'Ridgeback',
  'K-9',
  'Proper Chopper',
  'Mastiff Limited Edition',
  'Boxer',
  'Pro Street',
  'K9 Chopper',
  'K-9 124 Level 3 Graphics  BIG DOG IS BACK',
  'K-9 124  BIG DOG IS BACK',
  'custom'],
 ['ulysses',
  'EBR 1190RX',
  'Blast',
  '1125 CR',
  '1125R',
  'Lightning',
  'Ulysses',
  'UlyssesВ®',
  'Other',
  'Thunderbolt'],
 ['Brutale 1090',
  'Brutale',
  'Brutale 800',
  'F4 1000R',
  'Brutale 800 EAS',
  'Stradale 800',
  'Brutale 800 Dragster'],
 ['Classic Battle Green',
  'Classic',
  '750 Interceptor',
  'Interceptor Series 1A',
  'B5 BULLET',
  'Classic 500',
  'Classic Chrome Export',
  'Interceptor T.T. 7',
  'Bullet 500 EFI'],
 ['LSC', 'Texas Chopper', 'AMERICAN IRONHORSE', 'TEJAS'],
 ['LOW BLOW STREET SWEEPER', 'Low Blow', 'Rude', 'python chopper'],
 ['350 RR-S', '125 RR-S', '300RR', '520RS'],
 ['Husqvarana', '250 WR', '250WR', 'TR 650'],
 ['Slingshot Sl',
  'SlingshotВ® SLR Orange Madness',
  'Slingshot SL',
  'RZR XP 1000 EPS'],
 ['Commando 850', 'Hi-Rider', 'N15CS'],
 ['SB6R', 'SB8R'],
 ['Rupp Roaster II', 'Chopper Bobber'],
 ['CUSHMAN', 'Pacemaker', 'Airborne'],
 ['GV250 AQUILA', 'ST7', 'GT650 R'],
 ['Gold Star', 'Lightning', 'VICTOR'],
 ['TNT 600'],
 ['946 Bellissima 150 3V'],
 ['Legend Managers Special', 'Tejas'],
 ['Rigid'],
 ['Bar Chopper'],
 ['Gunslinger'],
 ['32 Victory'],
 ['Metralla Mk II'],
 ['BHC-9 Coupe Trike'],
 ['Jimmy'],
 ['GTX-F LTD 1']]

    motor_brand = ttk.Combobox(carwind, width=10, value=(brands))
    motor_brand.place(x=200, y=230)

    def callback(eventObject):
        abc = eventObject.widget.get()
        motor = motor_brand.get()
        index = brands.index(motor)
        motor_model.config(values=models[index])

    motor_model = ttk.Combobox(carwind, width=10)
    motor_model.place(x=350, y=230)
    motor_model.bind('<Button-1>', callback)
    button = Button(carwind, text='Оценить', fg='green', command=test).place(x=500, y = 200, width=60, height = 30)
    carwind.mainloop()


